"""Export stage.

Writes the human and machine-readable artifacts consumed by OpenCode:

- .ai-context/code-graph.json      (typed nodes + relationship edges)
- .ai-context/repository-map.json  (modules, files, symbols, APIs, deps)
- .ai-context/architecture.md      (readable system overview)
- .ai-context/stats.json           (small build metrics)
"""
from __future__ import annotations

import json
import time
from collections import defaultdict
from pathlib import Path

from config import ENTRYPOINTS, KEY_FLOWS, OUTPUT_DIR, PROJECT_NAME, REPO_ROOT
from graph_builder import module_of


def _write_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def build_module_map(parsed: dict, graph_records: dict) -> list[dict]:
    modules: dict[str, dict] = defaultdict(lambda: {
        "files": [], "functions": [], "methods": [], "classes": [], "apis": [], "dependencies": set(),
    })

    for relpath, ast in parsed.items():
        mod = module_of(relpath)
        modules[mod]["files"].append(relpath)
        modules[mod]["functions"].extend(s.name for s in ast.symbols if s.kind == "function")
        modules[mod]["methods"].extend(f"{s.detail}.{s.name}" if s.detail else s.name
                                       for s in ast.symbols if s.kind == "method")
        modules[mod]["classes"].extend(s.name for s in ast.symbols if s.kind in {"class", "entity"})
        for api in ast.apis:
            modules[mod]["apis"].append(f"{api['method']} {api['path']}")

    # Resolve module -> module dependencies from graph MODULE_DEPENDS edges.
    for edge in graph_records["edges"]:
        if edge["relation"] == "MODULE_DEPENDS":
            src, dst = edge["source"], edge["target"]
            if src in modules and dst in modules and src != dst:
                modules[src]["dependencies"].add(dst)

    ordered = sorted(modules.keys())
    return [
        {
            "name": m,
            "files": sorted(modules[m]["files"]),
            "functions": _dedupe(modules[m]["functions"]),
            "methods": _dedupe(modules[m]["methods"]),
            "classes": _dedupe(modules[m]["classes"]),
            "apis": _dedupe(modules[m]["apis"]),
            "dependencies": sorted(modules[m]["dependencies"]),
            "file_count": len(modules[m]["files"]),
        }
        for m in ordered
    ]


def _dedupe(items) -> list[str]:
    seen = set()
    out = []
    for it in items:
        if it not in seen:
            seen.add(it)
            out.append(it)
    return out


def build_api_overview(parsed: dict) -> list[dict]:
    apis = {}
    for ast in parsed.values():
        for api in ast.apis:
            key = (api["method"], api["path"])
            apis.setdefault(key, []).append(ast.path)
    return [
        {"method": m, "path": p, "implemented_in": files}
        for (m, p), files in sorted(apis.items(), key=lambda kv: kv[0][0])
    ]


def _markdown_table(header: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines += ["| " + " | ".join(map(str, r)) + " |" for r in rows]
    return "\n".join(lines)


def build_architecture_md(modules: list[dict], api_overview: list[dict], stack: dict) -> str:
    lines = [
        f"# {PROJECT_NAME} — Architecture",
        "",
        "Auto-generated by `tools/code-intelligence`. Regenerate with",
        "`tools/code-intelligence/generate-code-map.ps1` or "
        "`python tools/code-intelligence/run.py`.",
        "",
        "## System overview",
        f"{PROJECT_NAME} is a food-marketplace application. The codebase is split into a "
        "NestJS backend (`server/`) and a Vue 3 SPA frontend (`client/`), with shared "
        "configuration, deployment files and documentation at the repo root.",
        "",
        "## Stack",
        "",
    ]
    rows = [[lang, str(count)] for lang, count in stack.get("by_language", {}).items()]
    lines.append(_markdown_table(["Language", "Files"], rows))
    lines.append("")
    lines.append("## Entry points")
    lines.append("")
    for area, files in ENTRYPOINTS.items():
        lines.append(f"- **{area}**: " + ", ".join(f"`{f}`" for f in files))
    lines.append("")
    lines.append("## Modules")
    lines.append("")
    rows = [[m["name"], m["file_count"], ", ".join(m["classes"]) or "-",
             ", ".join(m["functions"])[:80] or "-", ", ".join(m["dependencies"]) or "-"]
            for m in modules if m["file_count"] > 0]
    lines.append(_markdown_table(["Module", "Files", "Classes", "Functions", "Depends on"], rows))
    lines.append("")
    lines.append("## API surface")
    lines.append("")
    api_rows = [[a["method"], a["path"], ", ".join(a["implemented_in"])] for a in api_overview]
    lines.append(_markdown_table(["Method", "Path", "Where"], api_rows))
    lines.append("")
    lines.append("## Key flows")
    lines.append("")
    for flow in KEY_FLOWS:
        lines.append(f"- **{flow['name']}** — `{', '.join(flow['modules'])}`: {flow['summary']}")
    lines.append("")
    lines.append("For the deeper walkthrough of each flow see `tools/code-intelligence/docs/codebase-analysis.md`.")
    lines.append("")
    disp_flows = [[f["name"], ", ".join(f["modules"])] for f in KEY_FLOWS]
    lines.append(_markdown_table(["Flow", "Modules"], disp_flows))
    return "\n".join(lines) + "\n"


def export(parsed: dict, graph_records: dict, stack: dict, root: Path | None = None) -> list[Path]:
    out_dir = Path(root or OUTPUT_DIR)
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    p = out_dir / "code-graph.json"
    _write_json(p, graph_records)
    written.append(p)

    modules = build_module_map(parsed, graph_records)
    api_overview = build_api_overview(parsed)
    repo_map = {
        "project": PROJECT_NAME,
        "generated_at": time.time(),
        "stack": stack,
        "entrypoints": ENTRYPOINTS,
        "modules": modules,
        "api_overview": api_overview,
    }
    p = out_dir / "repository-map.json"
    _write_json(p, repo_map)
    written.append(p)

    p = out_dir / "architecture.md"
    p.write_text(build_architecture_md(modules, api_overview, stack), encoding="utf-8")
    written.append(p)

    p = out_dir / "stats.json"
    parsed_bytes = sum((Path(REPO_ROOT / rel).stat().st_size) for rel in parsed if (REPO_ROOT / rel).exists())
    _write_json(p, {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "files": stack.get("total_files", 0),
        "bytes": stack.get("total_bytes", 0),
        "modules": len(modules),
        "api_routes": len(api_overview),
        "parsed_source_bytes": parsed_bytes,
    })
    written.append(p)

    return written


from datetime import datetime  # noqa: E402